### ISSUE TITLE
Note that Improviz has been depreciated by original contributor since Jan 03, 2023

### ISSUE THREAD

**Issue by Ross-Li** [LimeLimeW/awesome-vjing#8]
![image](https://github.com/LimeLimeW/awesome-vjing/assets/61273074/84111afa-835d-4f2c-85cf-e03208486eef)
https://github.com/rumblesan/improviz

**Comment by LimeLimeW** [comment]
Whoops, I missed the issue ! Indeed, it has been deprecated. Thank you @Ross-Li !

See : https://github.com/LimeLimeW/awesome-vjing/commit/0f85a60927e00523c3158123d374e74dafea4e73
